Teachers_PET/config/routes.rb
Rails.application.routes.draw do
  
  resources :holidays
  resources :periods
  resources :timetables
  resources :passwords, controller: "passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
    controller: "passwords",
    only: [:create, :edit, :update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  get 'pages/index'
  get 'pages/home_page'
  post "/" => 'pages#set_current_timetable'
  get "/settings" => "pages#settings", as: "settings"

  resources :pages, only: [:home_page]
  
  constraints Clearance::Constraints::SignedIn.new do
    root to: 'pages#home_page', as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: 'pages#index'
  end

end

Teachers_PET/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'Teachers_PET', root_path, class: 'navbar-brand', id: "logo" %>
      </div>
      <div id="navbar">
        <% if signed_in? %>
          <ul class="nav navbar-nav">
            <%= form_tag root_path, class: 'timetable_select' do %>
              <%= select_tag 'set_timetable',
               options_from_collection_for_select(current_user.timetables, "id", "name", current_user.selected_timetable_id),
                onchange: 'this.form.submit()' %>
              <%= submit_tag 'submit' %>
              <%= javascript_tag "$('.timetable_select input').hide()" %>
            <% end %>
          </ul>
        <% end %>

        <ul class="nav navbar-nav pull-right">
          <% if signed_in? %>
            <li><span id="banner-username"><%= current_user.email %></span></li>
            <li><%= link_to 'Sign out', sign_out_path, method: :delete %></li>
            <li><%= link_to 'Settings', settings_path %></li>
          <% else %>
            <li><%= link_to 'Sign in', sign_in_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
</header>

Teachers_PET/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teachers_PET</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class='<%= controller.controller_name %>'>
    <%= render 'layouts/header' %>
    <p id="notice"><%= notice %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>