Teachers_PET/config/routes.rb
Rails.application.routes.draw do
  
  resources :holidays
  resources :periods
  resources :timetables
  resources :passwords, controller: "passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
    controller: "passwords",
    only: [:create, :edit, :update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  get 'pages/index'
  get 'pages/home_page'
  post "/" => 'pages#set_current_timetable'
  get "/settings" => "pages#settings", as: "settings"

  resources :pages, only: [:home_page]
  
  constraints Clearance::Constraints::SignedIn.new do
    root to: 'pages#home_page', as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: 'pages#index'
  end

end

Teachers_PET/app/controllers/timetables_controller.rb
class TimetablesController < ApplicationController
  before_action :require_login
  before_action :set_timetable, only: [:show, :edit, :update, :destroy]

  # GET /timetables
  # GET /timetables.json
  def index
    @timetables = current_user.timetables.all
  end

  # GET /timetables/1
  # GET /timetables/1.json
  def show
  end

  # GET /timetables/new
  def new
    @timetable = Timetable.new
  end

  # GET /timetables/1/edit
  def edit
  end

  # POST /timetables
  # POST /timetables.json
  def create
    @timetable = current_user.timetables.new(timetable_params)

    respond_to do |format|
      if @timetable.save
        format.html { redirect_to settings_path, notice: 'Timetable was successfully created.' }
        format.json { render :show, status: :created, location: @timetable }
      else
        format.html { render :new }
        format.json { render json: @timetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timetables/1
  # PATCH/PUT /timetables/1.json
  def update
    respond_to do |format|
      if @timetable.update(timetable_params)
        format.html { redirect_to settings_path, notice: 'Timetable was successfully updated.' }
        format.json { render :show, status: :ok, location: @timetable }
      else
        format.html { render :edit }
        format.json { render json: @timetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timetables/1
  # DELETE /timetables/1.json
  def destroy
    @timetable.destroy
    respond_to do |format|
      format.html { redirect_to timetables_url, notice: 'Timetable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timetable
      @timetable = Timetable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timetable_params
      params.require(:timetable).permit(:user_id, :year_start, :year_end, :name, :school)
    end
    
end

Teachers_PET/app/helpers/timetables_helper.rb
module TimetablesHelper
end

Teachers_PET/app/views/timetables/_form.html.erb
<%= form_for(@timetable) do |f| %>
  <% if @timetable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timetable.errors.count, "error") %> prohibited this timetable from being saved:</h2>

      <ul>
      <% @timetable.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :school %><br>
    <%= f.text_field :school %>
  </div>
  
  <div class="field">
    <%= f.label :year_start %><br>
    <%= f.date_select :year_start %>
  </div>
  <div class="field">
    <%= f.label :year_end %><br>
    <%= f.date_select :year_end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Teachers_PET/app/views/timetables/_timetable.html.erb
<td><%= link_to 'Edit', edit_timetable_path(timetable) %> | 
    <% if @timetables.count > 1 then %>
      <%= link_to 'Delete', timetable, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
</td>
<td><%= timetable.year_start %></td>
<td><%= timetable.year_end %></td>
<td><%= timetable.name %></td>
<td><%= timetable.school %></td>

Teachers_PET/app/views/timetables/edit.html.erb
<h1>Editing Timetable</h1>

<%= render 'form' %>


<%= link_to 'Back', settings_path %>

Teachers_PET/app/views/timetables/index.html.erb
<h3>Timetables</h3>

<table>
  <thead>
    <tr>
      <th class="col-md-1"> </th>
      <th class="col-md-1">Year start</th>
      <th class="col-md-1">Year end</th>
      <th class="col-md-4">Name</th>
      <th class="col-md-3">School</th>
       <th class="col-md-2"> </th>
    </tr>
  </thead>

  <tbody>
    <% @timetables.each do |timetable| %>
      <tr>
        <%= render timetable %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timetable', new_timetable_path %>

Teachers_PET/app/views/timetables/new.html.erb
<h1>New Timetable</h1>

<%= render 'form' %>

<%= link_to 'Back', timetables_path %>

Teachers_PET/app/views/timetables/show.html.erb
<p>
  <strong>Year start:</strong>
  <%= @timetable.year_start %>
</p>

<p>
  <strong>Year end:</strong>
  <%= @timetable.year_end %>
</p>

<p>
  <strong>Name:</strong>
  <%= @timetable.name %>
</p>

<p>
  <strong>School:</strong>
  <%= @timetable.school %>
</p>

<%= link_to 'Edit', edit_timetable_path(@timetable), {:class => "edit_link"} %> 
<%= link_to 'Back', timetables_path %>