Teachers_PET/config/routes.rb
Rails.application.routes.draw do
  
  resources :holidays
  resources :periods
  resources :timetables
  resources :passwords, controller: "passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
    controller: "passwords",
    only: [:create, :edit, :update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  get 'pages/index'
  get 'pages/home_page'
  post "/" => 'pages#set_current_timetable'
  get "/settings" => "pages#settings", as: "settings"

  resources :pages, only: [:home_page]
  
  constraints Clearance::Constraints::SignedIn.new do
    root to: 'pages#home_page', as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: 'pages#index'
  end

end

Teachers_PET/app/models/period.rb
class Period < ActiveRecord::Base
  belongs_to :timetable
    
  validates :name, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :timetable_id, presence: true
    
  validate :start_time_must_be_before_end_time
    
  def start_time_display
    apply_time_formatting read_attribute(:start_time)
  end
    
  def end_time_display
    apply_time_formatting read_attribute(:end_time)
  end
    
  private
    
  def apply_time_formatting(the_time)
    the_time.strftime("%H:%M")
  end
    
  def start_time_must_be_before_end_time
    if !self.start_time.nil? && !self.end_time.nil? then
      errors[:base] << "end time must be after start time" unless self.end_time > self.start_time
    end
  end
end

Teachers_PET/app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  before_action :require_login
  before_action :set_period, only: [:show, :edit, :update, :destroy]

  # GET /periods
  # GET /periods.json
  def index
    @periods = Period.all
  end

  # GET /periods/1
  # GET /periods/1.json
  def show
  end

  # GET /periods/new
  def new
    @period = Period.new
  end

  # GET /periods/1/edit
  def edit
  end

  # POST /periods
  # POST /periods.json
  def create
    timetable = Timetable.find(current_user.selected_timetable_id)
    @period = timetable.periods.new(period_params)

    respond_to do |format|
      if @period.save
        format.html { redirect_to settings_path, notice: 'Period was successfully created.' }
        format.json { render :show, status: :created, location: @period }
      else
        format.html { render :new }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /periods/1
  # PATCH/PUT /periods/1.json
  def update
    respond_to do |format|
      if @period.update(period_params)
        format.html { redirect_to settings_path, notice: 'Period was successfully updated.' }
        format.json { render :show, status: :ok, location: @period }
      else
        format.html { render :edit }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /periods/1
  # DELETE /periods/1.json
  def destroy
    @period.destroy
    respond_to do |format|
      format.html { redirect_to settings_path, notice: 'Period was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_period
      @period = Period.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def period_params
      params.require(:period).permit(:name, :start_time, :end_time, :timetable_id)
    end
end

Teachers_PET/app/helpers/periods_helper.rb
module PeriodsHelper
end

Teachers_PET/app/views/periods/_form.html.erb
<%= form_for(@period) do |f| %>
  <% if @period.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@period.errors.count, "error") %> prohibited this period from being saved:</h2>

      <ul>
      <% @period.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.time_select :start_time,{minute_step: 5, :default => {:hour => '9', :minute => '00'}} %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.time_select :end_time,{minute_step: 5, :default => {:hour => '10', :minute => '00'}} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Teachers_PET/app/views/periods/edit.html.erb
<h1>Editing Period</h1>

<%= render 'form' %>

<%= link_to 'Show', @period %> |
<%= link_to 'Back', periods_path %>

Teachers_PET/app/views/periods/index.html.erb
<h3>Listing Periods for "<%= Timetable.find(current_user.selected_timetable_id).name %>"</h3>

<table>
  <thead>
    <tr>
      <th class="col-md-1"></th>
      <th class="col-md-1">Start time</th>
      <th class="col-md-1">End time</th>
      <th class="col-md-3">Name</th>

      <th class="col-md-6"></th>
    </tr>
  </thead>

  <tbody>
    <% @periods.each do |period| %>
      <tr>
        <td><%= link_to 'Edit', edit_period_path(period) %> | <%= link_to 'Delete', period, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= period.start_time_display %></td>
        <td><%= period.end_time_display %></td>        
        <td><%= period.name %></td>


      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Period', new_period_path %>

Teachers_PET/app/views/periods/new.html.erb
<h1>New Period</h1>

<%= render 'form' %>

<%= link_to 'Back', periods_path %>

Teachers_PET/app/views/periods/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @period.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @period.start_time_display %>
</p>

<p>
  <strong>End time:</strong>
  <%= @period.end_time_display %>
</p>


<%= link_to 'Edit', edit_period_path(@period) %> |
<%= link_to 'Back', periods_path %>