Teachers_PET/config/routes.rb
Rails.application.routes.draw do
  
  resources :holidays
  resources :periods
  resources :timetables
  resources :passwords, controller: "passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
    controller: "passwords",
    only: [:create, :edit, :update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  get 'pages/index'
  get 'pages/home_page'
  post "/" => 'pages#set_current_timetable'
  get "/settings" => "pages#settings", as: "settings"

  resources :pages, only: [:home_page]
  
  constraints Clearance::Constraints::SignedIn.new do
    root to: 'pages#home_page', as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: 'pages#index'
  end

end

Teachers_PET/app/models/holiday.rb
class Holiday < ActiveRecord::Base
  belongs_to :timetable
  
  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :timetable_id, presence: true
  
  validate :start_date_must_be_before_end_date
  
  private
   
  def start_date_must_be_before_end_date
    unless self.start_date.nil? || self.end_date.nil? 
      errors[:base] << "end time must be after start time" unless self.end_date > self.start_date
    end
  end 
end

Teachers_PET/app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :require_login
  before_action :set_holiday, only: [:show, :edit, :update, :destroy]

  # GET /holidays
  # GET /holidays.json
  def index
    @holidays = Holiday.all
  end

  # GET /holidays/1
  # GET /holidays/1.json
  def show
  end

  # GET /holidays/new
  def new
    @holiday = Holiday.new
  end

  # GET /holidays/1/edit
  def edit
  end

  # POST /holidays
  # POST /holidays.json
  def create
    timetable = Timetable.find(current_user.selected_timetable_id)
    @holiday = timetable.holidays.new(holiday_params)

    respond_to do |format|
      if @holiday.save
        format.html { redirect_to settings_path, notice: 'Holiday was successfully created.' }
        format.json { render :show, status: :created, location: @holiday }
      else
        format.html { render :new }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holidays/1
  # PATCH/PUT /holidays/1.json
  def update
    respond_to do |format|
      if @holiday.update(holiday_params)
        format.html { redirect_to settings_path, notice: 'Holiday was successfully updated.' }
        format.json { render :show, status: :ok, location: @holiday }
      else
        format.html { render :edit }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holidays/1
  # DELETE /holidays/1.json
  def destroy
    @holiday.destroy
    respond_to do |format|
      format.html { redirect_to settings_path, notice: 'Holiday was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_holiday
      @holiday = Holiday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def holiday_params
      params.require(:holiday).permit(:name, :start_date, :end_date, :timetable_id)
    end
end

Teachers_PET/app/helpers/holidays_helper.rb
module HolidaysHelper
end

Teachers_PET/app/views/holidays/_form.html.erb
<%= form_for(@holiday) do |f| %>
  <% if @holiday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@holiday.errors.count, "error") %> prohibited this holiday from being saved:</h2>

      <ul>
      <% @holiday.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Teachers_PET/app/views/holidays/edit.html.erb
<h1>Editing Holiday</h1>

<%= render 'form' %>


<%= link_to 'Back', settings_path %>

Teachers_PET/app/views/holidays/index.html.erb
<h3>Listing Holidays for "<%= Timetable.find(current_user.selected_timetable_id).name %>"</h3>

<table>
  <thead>
    <tr>
      <th class="col-md-1"></th>
      <th class="col-md-1">Start date</th>
      <th class="col-md-1">End date</th>
      <th class="col-md-4">Name</th>
      <th class="col-md-5"></th>
    </tr>
  </thead>

  <tbody>
    <% @holidays.each do |holiday| %>
      <tr>
        <td><%= link_to 'Edit', edit_holiday_path(holiday) %> | <%= link_to 'Delete', holiday, method: :delete, data: { confirm: 'Are you sure?' } %></td>        
        <td><%= holiday.start_date %></td>
        <td><%= holiday.end_date %></td>
        <td><%= holiday.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Holiday', new_holiday_path %>

Teachers_PET/app/views/holidays/new.html.erb
<h1>New Holiday</h1>

<%= render 'form' %>

<%= link_to 'Back', holidays_path %>

Teachers_PET/app/views/holidays/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @holiday.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @holiday.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @holiday.end_date %>
</p>



<%= link_to 'Edit', edit_holiday_path(@holiday) %> |
<%= link_to 'Back', holidays_path %>